name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE: ghcr.io/davidortegit123/tec-actions-test  # reemplaza con tu usuario

    steps:
      # 1️⃣ Obtener tu código
      - uses: actions/checkout@v4

      #  Configurar Docker Buildx
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Log in a GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Construir y subir imagen
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
