name: CI - Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/davidortegit123/tec-actions-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Obtener tu código
      - uses: actions/checkout@v4

      # 2️⃣ Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Log in a GHCR usando token personal
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: davidortegit123
          password: ${{ secrets.GHCR_TOKEN }}

          
      # 4️⃣ Construir y subir imagen
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
